apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: springboot-app
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/PHieu160105/PTUDDNWeek8.git'
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
